config/routes.rb
Rails.application.routes.draw do
  
  root to: 'welcome#index'

  devise_for :users

  resources :wikis
  resources :users, only: [:update]
  resources :charges, only: [:new, :create]
  resources :collaborators, only: [:create, :destroy]

  get 'downgrade' => 'subscriptions#downgrade', :as => :downgrade_subscription
  match 'wikis/:wiki_id/collaborators/:id', to: 'collaborators#create', via: [:post], as: :add_collaborator
  match 'wikis/:wiki_id/collaborators/:id', to: 'collaborators#delete', via: [:delete], as: :remove_collaborator
end

app/models/collaborator.rb
class Collaborator < ActiveRecord::Base

  belongs_to :wiki
  belongs_to :user
  
end

app/models/subscription.rb
class Subscription < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base

  after_initialize :init

  def init
    self.role ||= 'standard'
  end
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  has_many :collaborators
  has_many :wikis, through: :collaborators, dependent: :destroy
  has_many :subscriptions

  def admin?
    role == 'admin'
  end

  def standard?
    role == 'standard'
  end

  def premium?
    role == 'premium'
  end

  def save_stripe_customer_id(user, customer_id)
    user.customer_id = customer_id
    user.save
  end

  def get_stripe_customer_id(user)
    return user.customer_id
  end

  def upgraded?
    !standard?
  end
  
end

app/models/wiki.rb
class Wiki < ActiveRecord::Base
has_many :collaborators
has_many :users, through: :collaborators
  after_initialize :init

  def init
    self.private ||= false
  end

  belongs_to :user

  scope :visible_to, -> (user) { 
    if !user.present?
      publicly_viewable 
    elsif (user.role == 'admin' || user.role == 'premium') 
      all.private 
    else 
      publicly_viewable 
     end}
     
  scope :publicly_viewable, -> { where(private: false)}
  
  def public?
    self.private == false
  end
  
end

app/controllers/amount.rb
class Amount
  def self.default
    return 1500
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
 
  rescue_from Pundit::NotAuthorizedError do |exception|
     redirect_to root_url, alert: exception.message
   end

   def after_sign_in_path_for(resource)
    wikis_path
   end

   protected
 
   def configure_permitted_parameters
     devise_parameter_sanitizer.for(:sign_up) << :username
   end
end

app/controllers/charges_controller.rb
class ChargesController < ActionController::Base

 def create
  
   # Creates a Stripe Customer object, for associating
   # with the charge
   customer = Stripe::Customer.create(
     email: current_user.email,
     card: params[:stripeToken]
   )
 
   # Where the real magic happens
   charge = Stripe::Charge.create(
     customer: customer.id, # Note -- this is NOT the user_id in your app
     amount: Amount.default,
     currency: 'usd'
   )

   save_stripe_customer_id(current_user, customer.id)
 
   flash[:success] = "Thanks for all the money, #{current_user.email}! Feel free to pay me again."
   @user = current_user
   @user.role = 'premium'
   @user.save
   Subscription.create(
    user_id: current_user.id,
    subscription_end_date: Time.now + 1.month,
    auto_renew: true)
   redirect_to edit_user_registration_path(anchor: "subscription") # or wherever
 
 # Stripe will send back CardErrors, with friendly messages
 # when something goes wrong.
 # This `rescue block` catches and displays those errors.
 rescue Stripe::CardError => e
   flash[:error] = e.message
   redirect_to new_charge_path
 end

  def new
   @stripe_btn_data = {
     key: "#{ Rails.configuration.stripe[:publishable_key] }",
     description: "BigMoney Membership - #{current_user.username}",
     amount: Amount.default
   }
  end

end

app/controllers/collaborators_controller.rb
class CollaboratorsController < ApplicationController

  def create
    @wiki = Wiki.find(params[:wiki_id])
    @user = User.find(params[:id])
    @collaborator = Collaborator.create(:user => @user, :wiki => @wiki)
    redirect_to edit_wiki_path(@wiki)
  end

  def delete
    @wiki = Wiki.find(params[:wiki_id])
    @collaborator = @wiki.collaborators.where(user_id: params[:id]).first
    @collaborator.destroy
    redirect_to edit_wiki_path(@wiki)
  end


end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController

def downgrade
  @subscription = current_user.subscriptions.last
  @subscription.auto_renew = false    

  if @subscription.save
    flash[:notice] = "Subscription will terminate #{@subscription.subscription_end_date}"
  else 
    flash[:error] = "The site failed to cancel your subscription. Contact support at support.app.com"
  end

end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/controllers/wikis_controller.rb
class WikisController < ApplicationController
  before_action :set_wiki, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @wikis = Wiki.visible_to(current_user)
    authorize @wikis
    respond_with(@wikis)
  end

  def show
    authorize @wiki
    respond_with(@wiki)
  end

  def new
    @wiki = Wiki.new
    authorize @wiki
    respond_with(@wiki)
  end

  def edit
    @wiki = Wiki.find(params[:id])
    authorize @wiki
  end

  def create
    @wiki = Wiki.create(wiki_params)
    @wiki.user_id = current_user.id   
    @wiki.save
    authorize @wiki
    respond_with(@wiki)
  end

  def update
    @wiki.update(wiki_params)
    @wiki.save
    authorize @wiki
    respond_with(@wiki)
  end

  def destroy
    authorize @wiki
    @wiki.destroy
    respond_with(@wiki)
  end

  private
    def set_wiki
      @wiki = Wiki.find(params[:id])
    end

    def wiki_params
      params.require(:wiki).permit(:title, :body, :private)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def markdown_to_html(markdown)
    renderer = Redcarpet::Render::HTML.new
    extensions = {fenced_code_blocks: true}
    redcarpet = Redcarpet::Markdown.new(renderer, extensions)
    (redcarpet.render markdown).html_safe
  end
end

app/helpers/collaborators_helper.rb
module CollaboratorsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/wikis_helper.rb
module WikisHelper
end

app/views/charges/create.html.erb
<h2>Thanks, you paid <strong>$15.00</strong>!</h2>

app/views/charges/new.html.erb
 <%= form_tag charges_path do %>
   <h4>Click the button!</h4>
   <script class='stripe-button' src="https://checkout.stripe.com/checkout.js" data-key="<%= @stripe_btn_data[:key] %>" data-amount=<%= @stripe_btn_data[:amount] %> data-description="<%= @stripe_btn_data[:description] %>" ></script>
 <% end %>

app/views/collaborators/_create.html.erb
<% User.all.each do |u| %>
<tr>
  <td><%= u.username %></td>
  <% if @wiki.collaborators.pluck("user_id").include?(u.id) %>
    <td><%= link_to "Remove", remove_collaborator_path(@wiki.id, u.id), method: :delete%></td>
  <% else %>
    <td><%= link_to "Add", add_collaborator_path(@wiki.id, u.id), method: :post %></td>
  <% end %>
</tr>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blocipedia</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <div class="row clearfix">
     <div class="col-md-12 column">
      <ul class="nav nav-tabs customnav">
       <li><%= link_to "Blocipedia", root_path %></li>
       <li ><%= link_to "Wikis", wikis_path %></li>
       <div class='pull-right user-info'>
         <% if current_user %>                      
         Hello <%= link_to (current_user.username || current_user.email), edit_user_registration_path %>!  
         <%= link_to edit_user_registration_path, class: 'btn btn-primary btn-sm' do %>
         <span class="fa fa-user"></span>
         <% end %>

         <%= link_to destroy_user_session_path, method: :delete, class: 'btn btn-primary btn-sm' do %>
         <span class="fa fa-sign-out"></span>
         <% end %>

         <% else %>
         <%= link_to "Sign In", new_user_session_path %> or 
         <%= link_to "Sign Up", new_user_registration_path %>
         <% end %>
       </div>
     </ul>


     <% if flash[:notice] %>
     <div class="alert alert-success">
       <button type="button" class="close" data-dismiss="alert">&times;</button>
       <%= flash[:notice] %>
     </div>
     <% elsif flash[:error] %>
     <div class="alert alert-danger">
       <button type="button" class="close" data-dismiss="alert">&times;</button>
       <%= flash[:error] %>
     </div>
     <% elsif flash[:alert] %>
     <div class="alert alert-warning">
       <button type="button" class="close" data-dismiss="alert">&times;</button>
       <%= flash[:alert] %>
     </div>
     <% end %>

     <%= yield %>

   </div>
 </div>
</div>

</body>
</html>

app/views/subscriptions/_subscription.html.erb
<main class='content'>
<div class='row'>
<h1 class='h2 split-cell split-cell--fluid'>Subscription Status: <%= current_user.role %></h1>
</div>

<div class='jumbotron'>
<p>
<i class='icn icn--correct mrxs'>
<% unless current_user.upgraded? %>
<h2>Create Private Wikis with One Time Subscription</h2>
Subscribe
$15.00 <%= link_to "Upgrade", new_charge_path, class: "btn btn-primary" %>
<% else %>
<p>You currently have a subscription</p>
<div id="downgrade">  
<p> If you would like to downgrade click 
<%= link_to "Downgrade", :controller => :subscriptions, :action => :downgrade, class: "btn btn-primary", remote: true %> 
</p>
</div>
<% end %>
</i>
</p>
</div>

app/views/subscriptions/downgrade.html.erb
<div>
  You have downgraded your subscription
</div>
<div>
  <%= link_to "Wikis", wikis_path %>
</div>

app/views/welcome/index.html.erb
<div class="container">
<!-- Title -->
  <div class="row">
    <div class="col-lg-12">
      <h1 class="text-center">Blocipedia: Social, Markdown Wikis</h1>
    </div>
  </div>

  <!-- Jumbotron Header -->
  <div class="row cleafix">
  <div class="col-md-2 column">
  </div>
  <div class="col-md-8 column">
  <div class="jumbotron">
    <h2 class="text-center">Create and Share Markdown Wikis</h2>
    <%= link_to "Sign Up", new_user_registration_path, class: "btn btn-primary btn-large" %>
  </div>
</div>
    <div class="col-md-2 column">
  </div>
</div>

  <hr>
  <!-- Page Features -->
  <div class="row text-center">

    <div class="col-md-3 col-sm-6 hero-feature">
    </div>

    <div class="col-md-3 col-sm-6 hero-feature">
      <div class="thumbnail">
        <img src="https://cdn2.iconfinder.com/data/icons/windows-8-metro-style/128/one_free.png" alt="">
        <div class="caption">
          <h3>Free Plan</h3>
          <p>Create unlimited public wikis!</p>
          <p>
            <%= link_to "Free Now!", new_user_registration_path, class: "btn btn-primary" %>
          </p>
        </div>
      </div>
    </div>

    <div class="col-md-3 col-sm-6 hero-feature">
      <div class="thumbnail">
        <img src="https://cdn3.iconfinder.com/data/icons/google-material-design-icons/48/ic_wallet_membership_48px-128.png" alt="">
        <div class="caption">
          <h3>Premium Plan</h3>
          <p>Create private wikis!</p>
          <p>
            <%= link_to "Buy Now!", edit_user_registration_path(anchor: "subscription"), class: 'btn btn-primary btn-sm' %>
          </p>
        </div>
      </div>
    </div>

    <div class="col-md-3 col-sm-6 hero-feature">
    </div>

  </div>
</div>

app/views/wikis/_form.html.erb
<%= form_for @wiki, :html => { :class => "form-horizontal wiki" } do |f| %>

    <% if @wiki.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@wiki.errors.count, "error") %> prohibited this wiki from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @wiki.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :title, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :title, :class => 'form-control' %>
    </div>
    <%= error_span(@wiki[:title]) %>
  </div>
  <div class="control-group">
    <%= f.label :body, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :body, size: "60x12", :class => 'form-control' %>
    </div>
    <%= error_span(@wiki[:body]) %>
  </div>
  <%# The condition checks that you are admin or premium and the creator of the wiki unless you are creating a new wiki %>
  <% if current_user.upgraded? && (@wiki.user == current_user || @wiki.user.nil?) %>
  <div class="control-group">
    <%= f.label :private %>
    <div class="controls">
      <%= f.check_box :private %>
    </div>
  </div>
  <% end %>
  <div class='row'><br>
  <div class='col-md-4'>
  <%= f.submit :class => 'btn btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
            wikis_path, :class => 'btn btn-default' %>
  </div>
  </div>

<% end %>

<table>
<tr>
  <th> Name </th>
  <th> Add or Remove Collaborator <th>
</tr>
<%= render 'collaborators/create' %>
</table>

app/views/wikis/edit.html.erb
<%- model_class = Wiki -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/wikis/index.html.erb
<%- model_class = Wiki -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:title) %></th>
      <th><%= model_class.human_attribute_name(:body) %></th>
      <th><%= model_class.human_attribute_name(:user) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @wikis.each do |wiki| %>
      <tr>
        <td><%= markdown_to_html wiki.title %></td>
        <td><%= markdown_to_html truncate(wiki.body, length: 20) %></td>
        <td><%= wiki.user.username %></td>
        <td>
          
          <%= link_to t('.show', :default => t("helpers.links.show")),
                      wiki_path(wiki), :class => 'btn btn-primary btn-xs' %>

          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_wiki_path(wiki), :class => 'btn btn-default btn-xs' %>
          <% if policy(wiki).destroy? %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      wiki_path(wiki),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_wiki_path,
            :class => 'btn btn-primary' %>

app/views/wikis/new.html.erb
<%- model_class = Wiki -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/wikis/show.html.erb
<%- model_class = Wiki -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:title) %>:</strong></dt>
  <dd><%= markdown_to_html @wiki.title %></dd>
  <dt><strong><%= model_class.human_attribute_name(:body) %>:</strong></dt>
  <dd><%= markdown_to_html @wiki.body %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              wikis_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_wiki_path(@wiki), :class => 'btn btn-default' %>
<% if policy(@wiki).destroy? %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              wiki_path(@wiki),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
<% end %>